/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as container from "../container.js";
import type * as helpers from "../helpers.js";
import type * as http from "../http.js";
import type * as tensorflow_tf_model from "../tensorflow/tf_model.js";
import type * as tensorflow_fn from "../tensorflow_fn.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  container: typeof container;
  helpers: typeof helpers;
  http: typeof http;
  "tensorflow/tf_model": typeof tensorflow_tf_model;
  tensorflow_fn: typeof tensorflow_fn;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
